import type { Metadata } from "next";
import "./globals.css";
import ProvidersWrapper from "./providers-wrapper";


export const metadata: Metadata = {
  title: "Task Management Tool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <ProvidersWrapper>{children}</ProvidersWrapper>
      </body>
    </html>
  );
}
